### ISSUE TITLE
[Epic] DB ERD작성하기

### ISSUE THREAD

**Issue by BlackBean99** [JNU-econovation/econo-techblog#1]
* [ ] 요구사항 명세서 작성
* [ ] 개발 명세서 작성
* [ ] API Request DataType 정리
* [ ] ERD 작성
